// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAoikmdKNBhLxsphHKb0-_J8BnhFvrLyo',
    appId: '1:278432827614:web:fc83d8bcba65d9dffa5a4f',
    messagingSenderId: '278432827614',
    projectId: 'focusnflow-5d77d',
    authDomain: 'focusnflow-5d77d.firebaseapp.com',
    storageBucket: 'focusnflow-5d77d.firebasestorage.app',
    measurementId: 'G-TX2ERT3BVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWgXc5pAQUV20fGrIxQrk1RfvOTPQQrBE',
    appId: '1:278432827614:android:8256860071e02cc1fa5a4f',
    messagingSenderId: '278432827614',
    projectId: 'focusnflow-5d77d',
    storageBucket: 'focusnflow-5d77d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUcf68MFoZ2Kwbb1h5K-ajOD-SkftapiY',
    appId: '1:278432827614:ios:dee202e76ecd2ca2fa5a4f',
    messagingSenderId: '278432827614',
    projectId: 'focusnflow-5d77d',
    storageBucket: 'focusnflow-5d77d.firebasestorage.app',
    iosBundleId: 'com.example.focus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUcf68MFoZ2Kwbb1h5K-ajOD-SkftapiY',
    appId: '1:278432827614:ios:dee202e76ecd2ca2fa5a4f',
    messagingSenderId: '278432827614',
    projectId: 'focusnflow-5d77d',
    storageBucket: 'focusnflow-5d77d.firebasestorage.app',
    iosBundleId: 'com.example.focus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAoikmdKNBhLxsphHKb0-_J8BnhFvrLyo',
    appId: '1:278432827614:web:7af75e4ccf7ae8acfa5a4f',
    messagingSenderId: '278432827614',
    projectId: 'focusnflow-5d77d',
    authDomain: 'focusnflow-5d77d.firebaseapp.com',
    storageBucket: 'focusnflow-5d77d.firebasestorage.app',
    measurementId: 'G-4QN3PPJS6B',
  );
}
